name: Issue Ops Commands

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  actions: read
  issues: write

jobs:
  command:
    name: Issue Command
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      
      - name: Get active step workflow
        id: step-info
        uses: skills/exercise-toolkit/actions/active-step-workflow@get-current-step-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract state labels
        id: difficulty
        uses: FidelusAleksander/state-labels@v1
        with:
          operation: get
          key: difficulty
          issue-number: ${{ github.event.issue.number }}
          github-repository: ${{ github.repository }}

      - uses: github/command@v2.0.1
        id: hint-command
        with:
          command: ".hint"
          allowed_contexts: issue
          reaction: "eyes"

      - name: Comment with hint
        if: ${{ steps.hint-command.outputs.continue == 'true' && steps.difficulty.outputs.value == 'beginner' }}
        uses: GrantBirki/comment@v2.1.1
        with:
          issue-number: ${{ github.event.issue.number }}
          file: .github/hints/${{ steps.step-info.outputs.current-step }}.md

      - name: Comment if not beginner
        if: ${{ steps.hint-command.outputs.continue == 'true' && steps.difficulty.outputs.value != 'beginner' }}
        uses: GrantBirki/comment@v2.1.1
        with:
          issue-number: ${{ github.event.issue.number }}
          file: .github/hints/not-eligible.md

      - uses: github/command@v2.0.1
        id: difficulty-command
        with:
          command: ".difficulty"
          allowed_contexts: issue
          reaction: "eyes"

      - name: Parse difficulty level
        if: ${{ steps.difficulty-command.outputs.continue == 'true' }}
        id: parse-difficulty
        run: |
          # Extract the difficulty level from the command arguments
          ARGS="${{ steps.difficulty-command.outputs.command_arguments }}"
          if [[ "$ARGS" == "beginner" ]] || [[ "$ARGS" == "intermediate" ]]; then
            echo "new_difficulty=$ARGS" >> $GITHUB_OUTPUT
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "valid=false" >> $GITHUB_OUTPUT
          fi

      - name: Remove old difficulty label
        if: ${{ steps.difficulty-command.outputs.continue == 'true' && steps.parse-difficulty.outputs.valid == 'true' }}
        uses: issue-ops/labeler@v3
        with:
          action: remove
          issue_number: ${{ github.event.issue.number }}
          labels: state::difficulty::${{ steps.difficulty.outputs.value }}

      - name: Add new difficulty label
        if: ${{ steps.difficulty-command.outputs.continue == 'true' && steps.parse-difficulty.outputs.valid == 'true' }}
        uses: issue-ops/labeler@v3
        with:
          action: add
          issue_number: ${{ github.event.issue.number }}
          labels: state::difficulty::${{ steps.parse-difficulty.outputs.new_difficulty }}

      - name: Comment on successful difficulty change
        if: ${{ steps.difficulty-command.outputs.continue == 'true' && steps.parse-difficulty.outputs.valid == 'true' }}
        uses: GrantBirki/comment@v2.1.1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ✅ **Difficulty level changed successfully!**
            
            - Previous difficulty: `${{ steps.difficulty.outputs.value }}`
            - New difficulty: `${{ steps.parse-difficulty.outputs.new_difficulty }}`
            
            ${{ steps.parse-difficulty.outputs.new_difficulty == 'beginner' && 'You can now use `.hint` commands to get help with the exercises! 💡' || 'You have chosen the intermediate difficulty. Hints are not available at this level, but you can always change back to beginner if needed. 💪' }}

      - name: Comment on invalid difficulty command
        if: ${{ steps.difficulty-command.outputs.continue == 'true' && steps.parse-difficulty.outputs.valid == 'false' }}
        uses: GrantBirki/comment@v2.1.1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ❌ **Invalid difficulty level specified.**
            
            Please use one of the following valid difficulty levels:
            - `.difficulty beginner` - Get hints and additional guidance
            - `.difficulty intermediate` - Work through challenges independently
            
            Current difficulty: `${{ steps.difficulty.outputs.value }}`

